#!/usr/bin/env python3
"""
Daily Useful - No LLM needed, just real data
Fetches Hacker News top 5 + GitHub trending + creates daily note
Run daily: python3 daily_briefing.py
"""
import os, json, subprocess, datetime
from pathlib import Path
import urllib.request

ROOT = Path(__file__).parent
PROJECTS = ROOT / "projects" / "Project_daily"
OUTPUT = PROJECTS / "output"
OUTPUT.mkdir(parents=True, exist_ok=True)

today = datetime.datetime.now().strftime("%Y-%m-%d")
today_file = OUTPUT / f"{today}.md"

def fetch_hn():
    try:
        # Get top story IDs
        url = "https://hacker-news.firebaseio.com/v0/topstories.json"
        data = urllib.request.urlopen(url, timeout=10).read()
        ids = json.loads(data)[:5]
        stories = []
        for sid in ids:
            try:
                s_url = f"https://hacker-news.firebaseio.com/v0/item/{sid}.json"
                s_data = urllib.request.urlopen(s_url, timeout=5).read()
                s = json.loads(s_data)
                stories.append(f"- [{s.get('title')}]({s.get('url','https://news.ycombinator.com/item?id='+str(sid))}) ({s.get('score',0)} pts)")
            except:
                continue
        return stories
    except Exception as e:
        return [f"- HN fetch failed: {e}", "- https://news.ycombinator.com"]

def fetch_github_trending():
    # Simple fallback - use curl to gh trending page titles (no API key)
    try:
        # Try to get trending repos via GitHub API (no key, rate limited but works)
        req = urllib.request.Request("https://api.github.com/search/repositories?q=stars:>1&sort=stars&order=desc&per_page=3", headers={"User-Agent":"daily-briefing"})
        data = urllib.request.urlopen(req, timeout=10).read()
        j = json.loads(data)
        repos = [f"- {r['full_name']}: {r['description'][:80]} ({r['stargazers_count']}★)" for r in j.get('items',[])[:3]]
        return repos
    except Exception as e:
        return [f"- GitHub trending fetch failed: {e}"]

def get_yesterday():
    yesterday = (datetime.datetime.now() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")
    y_file = OUTPUT / f"{yesterday}.md"
    if y_file.exists():
        return y_file.read_text()[:1000]
    return "No yesterday file"

hn = fetch_hn()
gh = fetch_github_trending()
yesterday = get_yesterday()

content = f"""# Daily - {today}

## Morning - Created at {datetime.datetime.now().strftime('%H:%M')}

### Tasks Today (edit this)
- [ ] Check teamily.ai findings (in /home/user/findings/)
- [ ] Review SkillOS agents: `python3 universal_runtime.py agents`
- [ ] Pick 1 small goal and run `python3 universal_runtime.py execute "your goal"`

### Briefing - Hacker News Top 5
{chr(10).join(hn)}

### GitHub Trending Top 3
{chr(10).join(gh)}

### Yesterday Recap (first 1000 chars)
{yesterday[:500]}

---

## Evening Review (fill at 6pm)
- Done:
  - 
- Failed:
  - 
- Tomorrow:
  - 

## Useful Commands (copy-paste)
```bash
cd /home/user/skillos
python3 universal_runtime.py status          # system status
python3 universal_runtime.py agents | head   # list agents
python3 daily_briefing.py                    # regenerate this file
python3 universal_runtime.py execute "Create a tutorial on X"
ls projects/Project_daily/output/            # see all daily notes
cat findings/report.md | head -n 30          # your teamily.ai report
```

## SkillOS Universal Quick Start (daily)
- `python3 universal_runtime.py repl` -> interactive, type `help`
- `python3 universal_runtime.py execute "Monitor tech news and generate briefing"` -> creates project
- `ls .agents/` -> 49 universal agents ready
- `ls .skillos/skills/ | wc -l` -> 108 external skills

---
Generated by daily_briefing.py - no LLM, no API key, just real data
"""

today_file.write_text(content)
print(f"Created: {today_file}")
print(content)
